on: [push]

name: Code Coverage

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
      - id: coverage
        uses: actions-rs/grcov@v0.1
      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: ${{ steps.coverage.outputs.report }}
      - name: coverage-num
        run: echo "##[set-output name=data;]$( echo ${{ steps.coverage.outputs.report }})"
      - name: Custom badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: coverage
          LABEL: 'Updated at'
          STATUS: ${{ steps.coverage-num.outputs.data }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

